### ISSUE TITLE
[Suggestion] Include in Commit window context menu

### ISSUE THREAD

**Issue by dgomolka** [Drjacky/Avocado#112]

**Comment by Drjacky** [comment]
Thanks for your suggestion!
I will check the possibility of this and if it is possible, I'll implement it!
Meanwhile, feel free to open a PR

**Comment by Drjacky** [comment]
> Meanwhile, feel free to open a PR

I just found out about your [PR](https://github.com/Drjacky/Avocado/pull/113). Thanks, will check is asap!

**Comment by Drjacky** [comment]
https://github.com/Drjacky/Avocado/pull/113

**Comment by Drjacky** [comment]
@dgomolka Do you mean in the Commit Changes dialog? or Local Changes window?

**Comment by dgomolka** [comment]
Yeah I meant local changes 😄

**Comment by Drjacky** [comment]
https://github.com/Drjacky/Avocado/pull/113
