### ISSUE TITLE
Request: after optimization, also reformat the file using current settings of the project

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Drjacky/Avocado#116]
As the title says.
Or offer an option to do it.

**Comment by Drjacky** [comment]
But it decreases the optimization of the Avocado work. By reformating it after the Avocado, it breaks some lines.

**Comment by AndroidDeveloperLB** [comment]
But the work is already done. The files were optimized. That's now just formatting. 
Doesn't it get to a minimal size when generating the APK later, especially in release mode?
