### ISSUE TITLE
Move "Avocado-Size It" option

### ISSUE THREAD

**Issue by WildOrangutan** [Drjacky/Avocado#118]
Hey!

Really like your plugin, but I have a minor annoyance.

Can we move "Avocado-Size It" option down a bit? It disrupts my workflow, since I'm used to do "right click -> New". I usually by habit move my mouse on top of "New" option, without thinking. But with your plugin, "Avocado-Size It" is on that place.

![image](https://github.com/user-attachments/assets/e0d01b49-16b4-44c0-b5a6-13d5cc3d2df2)

**Comment by Drjacky** [comment]
Has been changed in [3.5.6](https://plugins.jetbrains.com/plugin/23263-avocado/versions/stable/614785)

**Comment by WildOrangutan** [comment]
Thank you!
