### ISSUE TITLE
Support Android Studio 242*

### ISSUE THREAD

**Issue by WildOrangutan** [Drjacky/Avocado#119]
After updating to Android Studio Ladybug | 2024.2.1, I get following error:

> Plugin 'Avocado' (version '3.5.6') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is AI-242.21829.142

**Comment by waffiqaziz** [comment]
Yup same, Not compatible with Android Studio Ladybug | 2024.2.1 Patch 1

**Comment by Drjacky** [comment]
This has been fixed on the next release, [3.5.7](https://github.com/Drjacky/Avocado/releases/tag/3.5.7)
